### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by sascham** [lululombard/ESP8266AntMinerStatus#1]
Hi,

i know the project is already couple years old, can i still ask you for some support?

In file included from sketch\LcdUtils.h:4:0,
                 from sketch\LcdUtils.cpp:1:
ESP8266WiFi.h:56:42: error: stray '\302' in program
   <title>Arduino/ESP8266WiFi.h at master · esp8266/Arduino · GitHub</title>
                                          ^
ESP8266WiFi.h:56:43: error: stray '\267' in program
   <title>Arduino/ESP8266WiFi.h at master · esp8266/Arduino · GitHub</title>
                                           ^
ESP8266WiFi.h:56:61: error: stray '\302' in program
   <title>Arduino/ESP8266WiFi.h at master · esp8266/Arduino · GitHub</title>
                                                             ^
ESP8266WiFi.h:56:62: error: stray '\267' in program
   <title>Arduino/ESP8266WiFi.h at master · esp8266/Arduino · GitHub</title>
                                                              ^
In file included from sketch\LcdUtils.h:4:0,
                 from sketch\LcdUtils.cpp:1:
C:\Users\smode\Documents\Arduino\libraries\Arduino_Uno_WiFi_Dev_Ed_Library\src/ESP8266WiFi.h:308:10: warning: missing terminating ' character
     </option></form><form class="js-site-search-form" role="search" aria-label="Site" data-scope-type="Repository" data-scope-id="32969220" data-scoped-search-url="/esp8266/Arduino/search" data-owner-scoped-search-url="/orgs/esp8266/search" data-unscoped-search-url="/search" action="/esp8266/Arduino/search" accept-charset="UTF-8" method="get">
          ^

**Comment by lululombard** [comment]
Hello! 
Thanks for trying my project!
I’ll try to compile it again if I have some time :)

**Comment by sascham** [comment]
worked :) sorry. my stupid, did not use sketch for a long time

**Comment by lululombard** [comment]
No problem! Glad that it still works! :)
